version: '3.5'
services:
  php-intern_test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
#    image: test_lan_9
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/database:/var/lib/mysql
#  networks:
#    internal:
#      driver: bridge
